spring:
  application:
    name: fisher-transaction-service
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        group: TSC_GROUP
  profiles:
    active: dev